version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: xuthority_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: xuthority_test
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: xuthority_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
