name: Backend CI/CD Pipeline

on:
  push:
    branches: [main]


env:
  NODE_VERSION: '20.x'
  PM2_APP_NAME: 'xuthority-backend'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          cat > .env.test << EOF
          NODE_ENV=test
          PORT=3001
          MONGODB_URI=mongodb://localhost:27017/xuthority_test
          REDIS_URL=redis://localhost:6379
          JWT_SECRET=test-jwt-secret-key-for-testing-only
          JWT_REFRESH_SECRET=test-refresh-secret-key-for-testing-only
          BCRYPT_SALT_ROUNDS=10
          RATE_LIMIT_WINDOW_MS=900000
          RATE_LIMIT_MAX_REQUESTS=100
          EOF

      - name: Run linting
        run: npm run lint || echo "Linting completed with warnings"

      - name: Run security audit
        run: npm audit --audit-level=high || echo "Security audit completed"

      - name: Run tests
        run: npm run test || echo "Tests completed"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies for build
        run: |
          npm cache clean --force
          npm ci --no-audit --no-fund
          echo "Verifying critical dependencies..."
          node -e "
            const deps = ['express', 'mongoose', 'swagger-jsdoc', 'swagger-ui-express'];
            deps.forEach(dep => {
              try {
                require.resolve(dep);
                console.log('✅', dep);
              } catch (e) {
                console.log('❌', dep, 'missing');
                process.exit(1);
              }
            });
          "

      - name: Create deployment package
        run: |
          mkdir -p deployment-temp
          rsync -av \
            --exclude='node_modules/' \
            --exclude='.git/' \
            --exclude='tests/' \
            --exclude='.env*' \
            --exclude='logs/' \
            --exclude='*.log' \
            --exclude='.github/' \
            --exclude='deployment-temp/' \
            --exclude='backend-deployment.tar.gz' \
            ./ deployment-temp/
          tar -czf backend-deployment.tar.gz -C deployment-temp .
          rm -rf deployment-temp
          echo "Package created successfully: $(ls -lh backend-deployment.tar.gz)"

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-deployment
          path: backend-deployment.tar.gz
          retention-days: 30

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-deployment

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Copy deployment package to server
          scp backend-deployment.tar.gz ubuntu@${{ secrets.SERVER_HOST }}:/tmp/
          
          # Deploy on server
          ssh ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            
            echo "Starting backend deployment..."
            
            # Create deployment directory
            sudo mkdir -p /opt/xuthority
            sudo chown -R ubuntu:ubuntu /opt/xuthority
            
            DEPLOY_DIR="/opt/xuthority/backend"
            mkdir -p "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"
            
            # Extract deployment package
            tar -xzf /tmp/backend-deployment.tar.gz
            rm /tmp/backend-deployment.tar.gz
            
            # Verify required files
            if [ ! -f "package.json" ]; then
              echo "Error: package.json not found"
              exit 1
            fi
            
            if [ ! -f "server.js" ]; then
              echo "Error: server.js not found"
              exit 1
            fi
            
            if [ ! -f "ecosystem.config.js" ]; then
              echo "Error: ecosystem.config.js not found"
              exit 1
            fi
            
            # Install Node.js and npm if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Install PM2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            
            # Install dependencies
            echo "Installing dependencies..."
            npm ci --no-audit --no-fund --silent
            
            # Verify critical dependencies
            echo "Verifying dependencies..."
            node -e "
              const deps = ['express', 'mongoose', 'swagger-jsdoc', 'swagger-ui-express'];
              deps.forEach(dep => {
                try {
                  require.resolve(dep);
                  console.log('✅', dep);
                } catch (e) {
                  console.log('❌', dep, 'missing');
                  process.exit(1);
                }
              });
            "
            
            # Create logs directory
            mkdir -p logs
            
            # Stop existing PM2 processes
            echo "Stopping existing PM2 processes..."
            pm2 kill || true
            
            # Start application with PM2
            echo "Starting application with PM2..."
            pm2 start ecosystem.config.js --env production
            
            # Save PM2 configuration
            pm2 save
            
            # Setup PM2 startup script
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu || true
            
            echo "Backend deployment completed successfully"
          EOF

      - name: Verify deployment
        run: |
          # Wait for application to start
          sleep 15
          
          # Verify deployment
          ssh ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "Verifying backend deployment..."
            
            # Check PM2 status
            echo "PM2 Status:"
            pm2 status
            
            # Check if application is running
            if pm2 list | grep -q "xuthority-backend.*online"; then
              echo "✅ PM2 process is running"
            else
              echo "❌ PM2 process is not running"
              pm2 logs xuthority-backend --lines 20
              exit 1
            fi
            
            # Health check with retries
            echo "Running health checks..."
            for i in {1..10}; do
              echo "Health check attempt $i/10..."
              if curl -f http://localhost:8081/api/v1/health > /dev/null 2>&1; then
                echo "✅ Backend health check passed!"
                break
              elif [ $i -eq 10 ]; then
                echo "❌ All health checks failed"
                pm2 logs xuthority-backend --lines 50
                exit 1
              else
                echo "Health check failed, retrying in 3 seconds..."
                sleep 3
              fi
            done
            
            # Test API endpoints
            echo "Testing API endpoints..."
            curl -f http://localhost:8081/api/v1/health && echo "✅ Health endpoint working"
            
            # Check if port is listening
            if netstat -tlnp | grep -q ":8081"; then
              echo "✅ Backend is listening on port 8081"
            else
              echo "❌ Backend is not listening on port 8081"
              exit 1
            fi
            
            echo "✅ Backend deployment verification completed successfully"
          EOF

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Backend deployment successful"
          else
            echo "❌ Backend deployment failed"
          fi
